#___________________________________________________________________________________________________________
# title: "INT2023_Bleaching"
# authors: "Ewout Knoester & Sara Sottoriva"
# date: "August 19, 2023"
# output: html_document
#___________________________________________________________________________________________________________

```{r setup inclue = "FALSE", message = "FALSE"}

rm(list=ls()) # Clear workspace
knitr::opts_knit$set(root.dir = '/tmp') #Set directory at current directory for all subsequent chunks

setwd("~/Documents/WUR/MASTER/#SARAINKENYA/2.EXPERIMENT/2.Bleaching")
getwd()

library(readxl)
library(tidyverse)
library(stringr) # remove spaces
library(panelr) # Convert data from wide to long
library(rstatix)
library(ggpubr)
library(ggthemes)
library(nlme) # mixed models allowing for heterogeneity
library(multcomp) # add significance levels to plot
library(emmeans) # Pairwise comparisons
library(NCmisc) # Check packages used
library(writexl)

# load first xls sheet
my_data.raw <- read_excel("INT2023_Bleaching_RAW.xlsx", sheet = 1)

# Function to facilitate averaging a dataset
data_summary <- function(data, varname, groupnames){
  require(plyr)
  summary_func <- function(x, col){
    c(mean = mean(x[[col]], na.rm=TRUE),
      sd = sd(x[[col]], na.rm=TRUE),
      n  = length(x[[col]]),
      se = sd(x[[col]], na.rm=TRUE)/sqrt(length(x)))
  }
  data_sum<-ddply(data, groupnames, .fun=summary_func,
                  varname)
  data_sum <- rename(data_sum, c("mean" = varname))
  return(data_sum)
}

```

```{r data preparation, inclue = "FALSE", message = "FALSE"}

### Data info ###
# Brightness expressed in bpp, where 0 = black and 255 = white
# Adjusted brightness: Correct brightness of fragment using brightness of slate, assuming slate should be 255 bpp
# Survival = Cover of live coral tissue per fragment
# AVG Brightness & AVG Survival = Average per 8 fragments (Tree)
# Diff Survival = Difference between End and Start survival

my_data.raw.1 <- as.data.frame(long_panel(my_data.raw, prefix = "_" , begin = 0, end = 1, label_location = "end"))

my_data.raw.1$Cause[my_data.raw.1$Survival > 0] <- NA # All fragments with Survival>0.0 are considered alive

# Select relevant columns: id, Tree, Treatment, Date, Adjusted brightness
my_data.B <- my_data.raw.1 %>% separate(Structure, c('Treatment', 'Tree')) # split Structure-column into Tree and Treatment

my_data.B <- my_data.B %>%
  dplyr::select(c("id", "Tree","Treatment", "Position", "Species",
           "Date", "Adjusted brightness (0 - 255)")) 

# Turn dates into number of days from start (07/02/2020)
startdate <- as.Date("2023/02/27", "%Y/%m/%d")
my_data.B$Date_days <- as.numeric(difftime(my_data.B$Date, startdate, units = "days"), units = "days")

# Fill Date diff with conditional values from Date_days: ie make start days a categorical variable (0,1,NA)
my_data.B$Date_diff <- ifelse(my_data.B$Date_days < 7, "0",
                   ifelse(my_data.B$Date_days < 50, "1","2"))

## Set date difference and rename
date.diff.order = c("0", 
                  "1", "2")
my_data.B %<>% 
  mutate(Date_diff = Date_diff %>% 
           factor(levels = date.diff.order))

# change headers of column bleaching
names(my_data.B)[7] <- "Bleaching"

# Make treatment and days factors
my_data.B$Treatment <- factor(my_data.B$Treatment, c("II", "IS", "SS", "SI"))
my_data.B$Tree <- factor(my_data.B$Tree)
my_data.B$Date_diff <- as.factor(my_data.B$Date_diff)
my_data.B$Position <- as.factor(my_data.B$Position)


# get insight into NAs
my_data.B %>%
  group_by(Treatment) %>%
  summarize(Sum_NA = sum(is.na(Bleaching)))

# removing rows containing NAs, thereby excluding Missing and Dead fragments, and missing pictures
my_data.B1 <- na.omit(my_data.B)

# get insight into NAs
my_data.B1 %>%
  group_by(Treatment) %>%
  summarize(Sum_NA = sum(is.na(Bleaching)))

write_xlsx(my_data.B1, "INT2023_Bleaching.xlsx")

```

```{r all fragments: data exploration}

# Import excel sheet
my_data.B1 <- read_excel("INT2023_Bleaching.xlsx", sheet = 1)

# Make treatment and days factors
my_data.B1$Treatment <- factor(my_data.B1$Treatment, c("II", "IS", "SS", "SI"))
my_data.B1$Tree <- factor(my_data.B1$Tree)
my_data.B1$Date_diff <- as.factor(my_data.B1$Date_diff)

# Visualizing data with box plots: heterogeneity likely over Date and Treatment
boxplot(Bleaching ~ Date, data = my_data.B1, xlab = "Date", ylab = "Brightness (bpp)")
boxplot(Bleaching ~ Treatment, data = my_data.B1, xlab = "Treatment", ylab = "Brightness (bpp)")
boxplot(Bleaching ~ Species, data = my_data.B1, xlab = "Species", ylab = "Brightness (bpp)")

# Normality tests: response data is rights skewed
ggqqplot(my_data.B1, x = "Bleaching")
hist(my_data.B1$Bleaching)

# visualizing log10(response) data with box plots: still heterogeneity likely over Date and Treatment
boxplot(log10(Bleaching)~Date, data = my_data.B1, xlab = "Date", ylab = "LOG10(Brightness(bpp))")
boxplot(log10(Bleaching)~Treatment, data = my_data.B1, xlab = "Treatment", ylab = "LOG10(Brightness(bpp))")
boxplot(log10(Bleaching)~Species, data = my_data.B1, xlab = "Species", ylab = "LOG10(Brightness(bpp))")

# normality test of log10(response): data is normally distributed
qqnorm(log10(my_data.B1$Bleaching))
qqline(log10(my_data.B1$Bleaching))
hist(log10(my_data.B1$Bleaching))

```

```{r all fragments: model selection}

# Import excel sheet
my_data.B1 <- read_excel("INT2023_Bleaching.xlsx", sheet = 1)

# Make treatment and days factors
my_data.B1$Treatment <- factor(my_data.B1$Treatment, c("II", "IS", "SS", "SI"))
my_data.B1$Tree <- factor(my_data.B1$Tree)
my_data.B1$Date_diff <- as.factor(my_data.B1$Date_diff)

# Full model with random structure for Structure and Date (using structure ID)
Model.all.log  <- lme(log10(Bleaching) ~ Treatment*Date_diff*Species, random = ~1|Tree, data = my_data.B1) #-2265.223	

# Full model allowing heterogeneity
Model.all.log2 <- lme(log10(Bleaching) ~ Treatment*Date_diff*Species, random = ~1|Tree, data = my_data.B1, weights = varIdent(form = ~1|Date_diff)) #-2286.765	

Model.all.log3 <- lme(log10(Bleaching) ~ Treatment*Date_diff*Species, random = ~1|Tree, data = my_data.B1, weights = varIdent(form = ~1|Treatment)) #-2327.913	

lmc <- lmeControl(niterEM = 5200, msMaxIter = 5200) # more iterations to reach convergence (will take some mins)

Model.all.log4 <- lme(log10(Bleaching) ~ Treatment*Date_diff*Species, random = ~1|Tree, data = my_data.B1, weights = varIdent(form = ~1|Treatment*Date_diff), control = lmc) #-2447.313	

# Allowing Treatment*Date_days heterogeneity best choice, despite increase in df:
AIC(Model.all.log, Model.all.log2, Model.all.log3, Model.all.log4)

Anova(Model.all.log4) # All variables are highly significant

```

```{r all fragments: model validation}

# Data is normally distributed
mod <- Model.all.log4 # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals
plot(my_data.B1$Date_diff, resid(mod, type = "pearson")) # residuals split over Date
abline(0,0)
plot(my_data.B1$Treatment, resid(mod, type = "pearson")) # residuals split over Treatment
abline(0,0)
plot(my_data.B1$Position, resid(mod, type = "pearson")) # residuals split over Genotype
abline(0,0)
plot(fitted(mod) ~ log10(my_data.B1$Bleaching)) # response (log) data vs fitted (log)
par(op)

```

```{r post hoc and plots}

### PLOT 1 - Treatment
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Treatment"))

# Create unique Finder for each Treatment combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Treatment,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.T <- emmeans(Model.all.log4, specs = pairwise ~ Treatment, adjust = "tuckey") 
letters.T <- multcomp::cld(hsd.T$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.T <- tibble::rownames_to_column(letters.T, "Group")
letters.T <- as.data.frame(append(letters.T,
     list(Finder = paste(letters.T$Treatment,
    sep=":")), after = 0))
letters.T <- letters.T[order(letters.T$Finder),]
letters.T <- letters.T %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.T$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Treatment 
Bleaching_Treatment <- ggplot(sum.all.log1, aes(x = Treatment, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Treatment")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Treatment, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100), expand = c(0, 0))

Bleaching_Treatment <- Bleaching_Treatment + coord_cartesian(ylim = c(0, 120)) #to reduce graph area

Bleaching_Treatment
ggsave("INT_Bleaching_Treatment.jpeg")


### PLOT 2 - SPECIES
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Species"))

# Create unique Finder for each Species combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Species,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.S <- emmeans(Model.all.log4, specs = pairwise ~ Species, adjust = "tuckey") 
letters.S <- multcomp::cld(hsd.S$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.S <- tibble::rownames_to_column(letters.S, "Group")
letters.S <- as.data.frame(append(letters.S,
     list(Finder = paste(letters.S$Species,
    sep=":")), after = 0))
letters.S <- letters.S[order(letters.S$Finder),]
letters.S <- letters.S %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.S$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Species 
Bleaching_Species <- ggplot(sum.all.log1, aes(x = Species, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Species")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Species, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100), expand = c(0, 0))

Bleaching_Species <- Bleaching_Species + coord_cartesian(ylim = c(0, 120))

Bleaching_Species
ggsave("INT_Bleaching_Species.jpeg")


### PLOT 3 - DATE
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Date_diff"))

# Create unique Finder for each Date combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Date_diff,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.D <- emmeans(Model.all.log4, specs = pairwise ~ Date_diff, adjust = "tuckey") 
letters.D <- multcomp::cld(hsd.D$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.D <- tibble::rownames_to_column(letters.D, "Group")
letters.D <- as.data.frame(append(letters.D,
     list(Finder = paste(letters.D$Date_diff,
    sep=":")), after = 0))
letters.D <- letters.D[order(letters.D$Finder),]
letters.D <- letters.D %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.D$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Date 
Bleaching_Date <- ggplot(sum.all.log1, aes(x = Date_diff, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Date")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Date_diff, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  scale_x_discrete(labels = c("02/2023", "06/2023")) +
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100), expand = c(0, 0))

Bleaching_Date <- Bleaching_Date + coord_cartesian(ylim = c(0, 120))

Bleaching_Date
ggsave("INT_Bleaching_Date.jpeg")


### PLOT 4 - DATE*TREATMENT
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Date_diff", "Treatment"))

# Create unique Finder for each Date*Treatment combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Date_diff, sum.all.log1$Treatment,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.DT <- emmeans(Model.all.log4, specs = pairwise ~ Date_diff|Treatment, adjust = "tuckey") 
letters.DT <- multcomp::cld(hsd.DT$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.DT <- tibble::rownames_to_column(letters.DT, "Group")
letters.DT <- as.data.frame(append(letters.DT,
     list(Finder = paste(letters.DT$Date_diff, letters.DT$Treatment,
    sep=":")), after = 0))
letters.DT <- letters.DT[order(letters.DT$Finder),]
letters.DT <- letters.DT %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.DT$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Date*Treatment
Bleaching_DatexTreatment <- ggplot(sum.all.log1, aes(x = Date_diff, fill = Treatment, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Date")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Date_diff, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  scale_x_discrete(labels = c("02/2023", "06/2023")) +
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100, 150), expand = c(0, 0))

Bleaching_DatexTreatment <- Bleaching_DatexTreatment + coord_cartesian(ylim = c(0, 150))

Bleaching_DatexTreatment
ggsave("INT_Bleaching_DatexTreatment.jpeg")


### PLOT 5 - DATE*SPECIES
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Date_diff", "Species"))

# Create unique Finder for each Date*Species combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Date_diff, sum.all.log1$Species,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.DS <- emmeans(Model.all.log4, specs = pairwise ~ Date_diff|Species, adjust = "tuckey") 
letters.DS <- multcomp::cld(hsd.DS$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.DS <- tibble::rownames_to_column(letters.DS, "Group")
letters.DS <- as.data.frame(append(letters.DS,
     list(Finder = paste(letters.DS$Date_diff, letters.DS$Species,
    sep=":")), after = 0))
letters.DS <- letters.DS[order(letters.DS$Finder),]
letters.DS <- letters.DS %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.DS$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Date*Species 
Bleaching_DatexSpecies <- ggplot(sum.all.log1, aes(x = Date_diff, fill = Species, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Date")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Date_diff, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#3A3A3A"))+
  scale_x_discrete(labels = c("02/2023", "06/2023")) +
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100, 150), expand = c(0, 0))

Bleaching_DatexSpecies <- Bleaching_DatexSpecies + coord_cartesian(ylim = c(0, 150))

Bleaching_DatexSpecies
ggsave("INT_Bleaching_DatexSpecies.jpeg")


### PLOT 6 - SPECIES*TREATMENT
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Species", "Treatment"))

# Create unique Finder for each Species*Treatment combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Species, sum.all.log1$Treatment,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.ST <- emmeans(Model.all.log4, specs = pairwise ~ Species|Treatment, adjust = "tuckey") 
letters.ST <- multcomp::cld(hsd.ST$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.ST <- tibble::rownames_to_column(letters.ST, "Group")
letters.ST <- as.data.frame(append(letters.ST,
     list(Finder = paste(letters.ST$Species, letters.ST$Treatment,
    sep=":")), after = 0))
letters.ST <- letters.ST[order(letters.ST$Finder),]
letters.ST <- letters.ST %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.ST$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Species*Treatment
Bleaching_SpeciesxTreatment <- ggplot(sum.all.log1, aes(x = Species, fill = Treatment, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Species")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Species, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100, 150), expand = c(0, 0))

Bleaching_SpeciesxTreatment <- Bleaching_SpeciesxTreatment + coord_cartesian(ylim = c(0, 150))

Bleaching_SpeciesxTreatment
ggsave("INT_Bleaching_SpeciesxTreatment.jpeg")


### PLOT 7 - TREATEMENT*SPECIES
# Get averages
sum.all.log1 <- data_summary(my_data.B1, varname = "Bleaching", groupnames = c("Treatment", "Species"))

# Create unique Finder for each Treatment*Species combination
sum.all.log1 <- as.data.frame(append(sum.all.log1,
    list(Finder = paste(sum.all.log1$Treatment, sum.all.log1$Species,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1 <- tibble::rownames_to_column(sum.all.log1, "ID")
sum.all.log1 <- sum.all.log1[order(sum.all.log1$Finder),]

# Post hoc comparison
hsd.TS <- emmeans(Model.all.log4, specs = pairwise ~ Treatment|Species, adjust = "tuckey") 
letters.TS <- multcomp::cld(hsd.TS$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.TS <- tibble::rownames_to_column(letters.TS, "Group")
letters.TS <- as.data.frame(append(letters.TS,
     list(Finder = paste(letters.TS$Treatment, letters.TS$Species,
    sep=":")), after = 0))
letters.TS <- letters.TS[order(letters.TS$Finder),]
letters.TS <- letters.TS %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1 <- cbind(sum.all.log1, siglet = letters.TS$.group)
sum.all.log1 <- sum.all.log1[order(as.numeric(sum.all.log1$ID)),]

## Plot Treatment*Species 
Bleaching_TreatmentxSpecies <- ggplot(sum.all.log1, aes(x = Treatment, fill = Species, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (0-255)")), x = "Treatment")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Treatment, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#3A3A3A"))+
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100, 150), expand = c(0, 0))

Bleaching_TreatmentxSpecies <- Bleaching_TreatmentxSpecies + coord_cartesian(ylim = c(0, 150))

Bleaching_TreatmentxSpecies
ggsave("INT_Bleaching_TreatmentxSpecies.jpeg")

```


```{r per species}

### ACROPORA TENUIS
# Selecting only Acropora data
Acro <- subset(my_data.B1, Species == "Acropora tenuis")

## Model selection
Model.all.log4.Acro <- lme(log10(Bleaching) ~ Treatment*Date_diff, random = ~1|Tree, data = Acro, weights = varIdent(form = ~1|Treatment*Date_diff), control = lmc)

Anova(Model.all.log4.Acro)

## Model validation
mod <- Model.all.log4.Acro # set model to be validated
op <- par(mfrow = c(2, 3), mar = c(5, 4, 1, 2)) # set layout of figure frame
plot(resid(mod, type = "pearson") ~ fitted(mod)) # fitted vs residuals
abline(0,0)
hist(resid(mod, type = "pearson"), main = "") # histogram residuals
qqnorm(resid(mod, type = "pearson")) # QQplot residuals

## Post hoc and plots
# Get averages
sum.all.log1.Acro <- data_summary(Acro, varname = "Bleaching", groupnames = c("Date_diff", "Treatment"))

# Create unique Finder for each Date*Treatment combination
sum.all.log1.Acro <- as.data.frame(append(sum.all.log1.Acro,
    list(Finder = paste(sum.all.log1.Acro$Date_diff, sum.all.log1.Acro$Treatment,
    sep=":")), after = 0))

# Create ID and order dataframe by name of Finder
sum.all.log1.Acro <- tibble::rownames_to_column(sum.all.log1.Acro, "ID")
sum.all.log1.Acro <- sum.all.log1.Acro[order(sum.all.log1.Acro$Finder),]

# Post hoc comparison
hsd.DT.Acro <- emmeans(Model.all.log4.Acro, specs = pairwise ~ Date_diff|Treatment, adjust = "tuckey") 
letters.DT.Acro <- multcomp::cld(hsd.DT.Acro$emmeans, alpha = 0.05, Letters = letters, decreasing = T) # get CLD

# Create ID and order dataframe by name (equals Finder of sgr.summary.TSD dataframe)
letters.DT.Acro <- tibble::rownames_to_column(letters.DT.Acro, "Group")
letters.DT.Acro <- as.data.frame(append(letters.DT.Acro,
     list(Finder = paste(letters.DT.Acro$Date_diff, letters.DT.Acro$Treatment,
    sep=":")), after = 0))
letters.DT.Acro <- letters.DT.Acro[order(letters.DT.Acro$Finder),]
letters.DT.Acro <- letters.DT.Acro %>% mutate(.group = str_squish(.group)) # remove white spaces

# Merge sig.letter dataframe into the summary dataframe
sum.all.log1.Acro <- cbind(sum.all.log1.Acro, siglet = letters.DT.Acro$.group)
sum.all.log1.Acro <- sum.all.log1.Acro[order(as.numeric(sum.all.log1.Acro$ID)),]

## Plot Date*Treatment
Bleaching_DatexTreatment_Acro <- ggplot(sum.all.log1.Acro, aes(x = Date_diff, fill = Treatment, y = Bleaching))+
  geom_bar(stat = "identity", position = position_dodge())+ 
  labs(y = expression(paste("Brightness (bpp)")), x = "Date")+ 
  geom_errorbar(aes(ymin=Bleaching-(1*se), ymax=Bleaching+(1*se)), width=.2,
                position=position_dodge(.9))+
  geom_text(data = sum.all.log1, aes(x=Date_diff, y = Bleaching + se+0.0015, label = siglet),vjust=-0.5, position = position_dodge(.9))+
  scale_fill_manual(values=c("#A9A9A9", "#7A7A7A", "#5A5A5A", "#3A3A3A"))+
  scale_x_discrete(labels = c("02/2023", "06/2023")) +
  theme_economist()+scale_colour_economist()+
  theme(
    axis.title.x = element_text(color="black", vjust=-2, size = 12),
    axis.text.x = element_text(angle = 0, size=12, face = "bold", vjust=0.5),
    axis.title.y = element_text(color="black" , vjust=0.5, hjust=0.5, size = 12),
    axis.text.y=element_text(size=12, face = "bold", vjust=0.5),
    )+
  scale_y_continuous(limits=c(0,230), breaks = c(0, 50, 100, 150), expand = c(0, 0))

Bleaching_DatexTreatment_Acro <- Bleaching_DatexTreatment_Acro + coord_cartesian(ylim = c(0, 150))

Bleaching_DatexTreatment_Acro
ggsave("INT_Bleaching_DatexTreatment_Acro.jpeg")




```


```{r: check packages used}

knitr::purl("Bleaching.Rmd")
list.functions.in.file("Bleaching.R")
unlink("Bleaching.R")

```
